comment_width = 100
imports_layout = "Vertical"
match_block_trailing_comma = true
max_width = 120
merge_imports = true
newline_style = "Unix"
use_field_init_shorthand = true
wrap_comments = true